name: flutter_introduction_workspace
description: The use case level package using both the flutter_introduction_widget and the flutter_introduction_service combined
version: 5.0.0

publish_to: None

environment:
  sdk: '>=3.1.0 <4.0.0'
dev_dependencies:
  melos: ">=3.0.1 <7.0.0"
