name: flutter_introduction_interface
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_data_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_data_interface.git
      ref: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
