name: shared_preferences_introduction_repository
description: "Shared_preference implementation of the introduction repository interface"
version: 6.0.0
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  introduction_repository_interface:
    path: ../introduction_repository_interface

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0






  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
