name: flutter_introduction
description: Combined Package of Flutter Introduction Widget and Flutter Introduction Service
version: 3.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_introduction_widget:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction
      ref: 3.1.0
      path: packages/flutter_introduction_widget
  flutter_introduction_service:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction
      ref: 3.1.0
      path: packages/flutter_introduction_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter: