name: flutter_introduction_service
description: A new Flutter package project.
version: 5.0.0
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_introduction_interface:
    hosted:  https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: "^5.0.0"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
